name: covid_care_app
description: Covid-19 exposure notification and anonymous contact tracing app.
publish_to: none
version: 1.0.0+1
environment:
  sdk: ">=2.7.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  #cloud_firestore: ^0.13.6
  firebase_auth: ^0.16.1
  intl_phone_number_input: ^0.4.2
  pin_code_fields: ^3.0.1
  device_info: ^0.4.2+4
  http: ^0.12.1
  font_awesome_flutter: ^8.8.1
  flare_splash_screen: ^3.0.1
  stacked: ^1.5.4
  stacked_services: ^0.3.2+1
  responsive_builder: ^0.2.0+2
  flutter_local_notifications: ^1.4.4+1
  shared_preferences: ^0.5.7+3
  injectable: ^0.4.0
  auto_route: ^0.5.0
  provider: ^4.1.2
  logger: ^0.9.1
  get_it: ^4.0.2
  equatable: ^1.1.1
  jiffy: ^3.0.1
  day: ^0.5.4
  background_locator: ^1.1.3+1
  location_permissions: ^2.0.5
  background_fetch: ^0.5.5
  slide_to_confirm: ^0.0.6
dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^0.5.0
  injectable_generator: ^0.4.0
  build_runner:
  flutter_launcher_icons: ^0.7.5
flutter:
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/flare/
    - assets/images/
flutter_icons:
  ios: true
  android: true
  image_path_ios: assets/launcher/icon.png
  image_path_android: assets/launcher/icon.png
  adaptive_icon_background: assets/launcher/background.png
  adaptive_icon_foreground: assets/launcher/foreground.png
  #  - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
